language: objective-c
osx_image: xcode9.3
script:
   - xcodebuild -project ELKeychain.xcodeproj -scheme ELKeychain -sdk iphonesimulator test -destination 'OS=11.1,name=iPhone X' CODE_SIGNING_REQUIRED=NO
